project:
  type: website
  output-dir: docs

website:
  title: "North Meck Community Research"
  navbar:
    background: "#3f4e75"
    right:
      - href: index.qmd
        text: Home
      - text: 2025 Data Dashboard
        menu: 
          - text: Childcare
            href: 2025-childcare.qmd
          - text: Education
            href: 2025-education.qmd
          - text: Housing
            href: 2025-housing.qmd
      - text: Previous Projects
        menu: 
          - text: Needs Assessment
            href: needs-assessment.qmd
          - text: 2022 Dashboard
            href: 2022-dashboard.qmd
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body: feedback-button.html
    link-external-icon: true
    link-external-newwindow: true

editor: visual

