project:
  type: website

website:
  title: "North Meck Community Research"
  navbar:
    background: "#3f4e75"
    right:
      - href: index.qmd
        text: Home
      - text: Projects
        menu: 
          - text: Needs Assessment
            href: needs-assessment.qmd
          - text: 2022 Dashboard
            href: 2022-dashboard.qmd
          - text: 2025 Dashboard
            href: 2025-dashboard.qmd
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
