---
title: "Community Research Open Data"
format: html
listing:
  type: grid
  sort: false
  grid-columns: 2
  contents: index.yml
---

In 2024, Mecklenburg ranked in the top 10 wealthiest counties in North Carolina. While families across Davidson, Cornelius, and Huntersville maintain high household incomes in comparison to the state average, North Mecklenburg is not monolithic. The perception that North Mecklenburg is exclusively wealthy leaves many families behind, including several communities of color.

A long history of segregation and redlining impacts residents in historically African American neighborhoods such as Pottstown, West Davidson, and Smithville, as well as the predominantly Hispanic/Latinx neighborhood Huntington Green. North Mecklenburg data often eclipses or excludes the experiences within these communities.

This website intends to provide more insight into the experiences of all North Mecklenburg residents, inclduing both resources and data analysis.

## Data equity

Data is not objective; researchers that collect, analyze, interpret, and distribute data hold subjective experiences and potential biases. Marginalized communities have historically faced unequal data access and disproportionate harm from data misuse. A data equity approach focuses on amplifying the voices and experiences of marginalized groups to actively combat this, applying a framework of diversity, equity, and inclusion.

## Community-based research

Community-based research is defined as a form of investigation in which the question arises from the needs of a group of individuals. The Community Research Fellows utilize a community-based research approach, including the voices of community members and leaders within data collection and presentation to produce the most comprehensive and accurate picture of North Mecklenburg possible.
